- app/components/ActionPanel.js
> Remove "Delegate" tab from Manager address view

- app/components/ActionPanel.js
- app/components/AddressBlock.js
> Change copy for the first-time user sidebar onboarding message.

- app/styles/global-styles.js
https://github.com/Cryptonomic/Tezos-Wallet/issues/95
> fix drag app problem

- app/components/Home.js
- app/components/TermsModal/index.js
> change copy trems and remove unncessary coma from topbar

- app/components/Delegate.js
> Add Delegation Tips to Delegated Address "Delegate" tab

- app/components/Addresses.js
- app/components/CreateAccountSlide/InputValidComponent.js
- app/components/CreateAccountSlide/index.js
- app/containers/HomeAddAddress/index.js
- app/styles/global-styles.js
Now, on a large screen the body of the transaction screen doesn't spread out uncontrollably.
> Adding max-width on the main frame of the app

- app/config.json
- app/containers/LoginHome/index.js
- app/main.dev.js
> Correctly brand the wallet

- app/components/AddressBlock.js
- app/components/Delegate/index.js
- app/components/DelegateConfirmationModal/index.js
- app/components/SendConfirmationModal.js
Couldn't find the official way of converting cycles into days in foundations documentation. I decided to use ~20 days.
Also, I changed Enter Password to Enter Wallet Password in modals to sustain consistency
> consistency with delegation cycles and passwords

- app/utils/i18n.js
- package-lock.json
- package.json
- webpack.config.renderer.prod.js
Copy locales folder to dist when building production, select the correct load path for the localization files
> Fix internationalization when packaging the app

- package-lock.json
- test/reduxContent/wallet/reducers.spec.js
> Wallet redux layer tests

- app/components/SettingsController/index.js
- app/components/TezosIcon/index.js
- extraResources/locales/en-US.json
First, I separated the words and icon of 'Settings' and 'Logout' buttons. 
Second, I added localizations for both words
> Separate the words and icon of 'Settings' and 'Logout' buttons. 

- app/components/Fees/index.js
- app/components/Send/index.js
- app/components/SendConfirmationModal/index.js
- app/components/SendLedgerConfirmationModal/index.js
- app/extraResources/locales/en-US.json
- app/package.json
- app/reduxContent/wallet/thunks.js
- app/yarn.lock
Need help with adding the Burn field to the modal.
Burn field should be added to both sendConfirmationModal and sendLedgerConfirmationModal
> improved send confirmation modal

- app/reduxContent/wallet/thunks.js
If account is already active, don't submit a duplicate activation
> "TypeError" issue

- app/components/ActionPanel/index.js
- app/components/AddDelegateModal/index.js
- app/components/DelegateConfirmationModal/index.js
- app/components/InputAddress/index.js
- app/components/InteractContractModal/InvokeContract.js
- app/components/Invoke/index.js
- app/components/Send/index.js
- app/components/TabContents/Delegate.jsx
- app/components/TabContents/InputError.jsx
- app/components/TabContents/WithdrawDeposit.jsx
- app/components/TabContents/style.js
- app/components/WithdrawDeposit/index.js
- app/constants/TabConstants.js
- app/extraResources/walletSettings.json
- app/reduxContent/generalThunk.js
- package.json
- yarn.lock
2: added the amount validation
> Separate delegation management UX for contracts

- app/components/AddDelegateModal/index.js
- app/components/BalanceBanner/index.js
- app/components/Delegate/index.js
- app/components/Fees/index.js
- app/components/InteractContractModal/DeployContract.js
- app/components/InteractContractModal/InvokeContract.js
- app/components/InteractContractModal/index.js
- app/components/Invoke/index.js
- app/components/InvokeManager/index.js
- app/components/Send/index.js
- app/components/TabContents/Delegate.jsx
- app/components/TabContents/WithdrawDeposit.jsx
- app/components/WithdrawDeposit/index.js
- app/extraResources/locales/en-US.json
2: converted some components to functional components
> 1: fixed the default fee

- README.md
Ensuring people know that they should hit the new codebase.
> Pointing README to T2

- .github/workflows/node.js.yml
Currently runs against a PoC branch.
> GitHub CI for Tezori v3

- .github/workflows/node.js.yml
- Allow manual runs of existing workflow
- Fix for branch name with slash
> Allow manual runs of Node.JS GitHub workflow

- .github/workflows/node.js.yml
> Another attempt to get NPM Action working

- .github/workflows/node.js.yml
> Fixing working directory for GitHub Actions
